### ISSUE TITLE
[php] PDO 관련 함수 정리

### ISSUE THREAD

**Issue by heowc** [heowc/programming-study#38]
php 에서는 통합 드라이버(?)인 **PDO**가 존재한다. 
extension만 추가하면 거의 모든 데이터베이스를 사용할 수 있다.

다양한 함수나 옵션을 제공하므로 간단하게 정리해보자.

**Comment by heowc** [comment]
php.ini 파일의 **pdo.dsn.~** 의 영향을 받는다.

**Comment by heowc** [comment]
다양한 상수 존재 [링크 참고](http://php.net/manual/kr/pdo.constants.php)

**Comment by heowc** [comment]
지속적인 연결 이나 커넥션 관리?
- unixODBC?
- Relay?
- apache의 mod_php
- FastCGI
- pdo - ATTR_PERSISTENT?


https://code.i-harness.com/ko/q/32d7ea

**Comment by heowc** [comment]
`PDO::ATTR_PERSISTENT -> true` 이면, 지속적인 연결하게 해주어 매번 커넥션을 만들지 않는다고 했다. 그렇다면 트랜잭션과 무슨 차이가 있을까?

롤백 차이?
보다 나은 성능?

**Comment by heowc** [comment]
PDO 객체 생성 시에 예외가 발생했지만 예외 처리를 하지 않으면 기본적으로 데이터베이스의 연결 세부 정보가 표시된다. 이를 해결하기 위해 **catch를 작성**하거나 **set_exception_handler**를 통해 예외를 포착해야 한다.

**Comment by heowc** [comment]
`PDO::ATTR_PERSISTENT -> true`는 좋지 못하다.

그 이유는 스크립트가 데이터베이스 작업 중간에 예기치 못하게 종료되는 경우, 이때, 아파치의 mod_php나 FastCGI를 사용한다면 연결이 끊기지 않는다. (PHP는 부모 프로세스에게 연결이 끊어 지도록 지시하지 않는다.)

**Comment by dbwodlf3** [comment]
맞아요. PDO::ATTR_PERISTENT Ture으로 해놓으니까 진짜... 아.. 뭐 이런게 다 있는지.
